# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ofo-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SWRevealViewController'
  pod 'AMapSearch'
  pod 'AMap3DMap'
  pod 'AMapLocation'
  pod 'AMapNavi'
 
  
  # Pods for ofo-Demo

end
